Update .pre-commit-config.yaml
brisbanesocialchess/awesome-social-chess pull request #56
Opened 2024-10-27 17:56 UTC by aniruddhaadak80

for issue #50

2024-10-27 17:59 UTC, jbampton commented on .pre-commit-config.yaml
> +  - repo: https://github.com/lojjic/pre-commit-ls-lint
404 Not Found

2024-10-27 18:02 UTC, aniruddhaadak80 commented
Fixing this .

2024-10-27 18:04 UTC, jbampton requested changes
Please only add one feature / one issue fix per PR

2024-10-27 18:10 UTC, aniruddhaadak80 commented
> Please only add one feature / one issue fix per PR

okey , I will . Sorry for inconvenience .

2024-10-27 18:13 UTC, jbampton commented
Hey @aniruddhaadak80 no need to be sorry.  You are doing great so far thanks !

If we have one feature / one fix / one issue per PR it will make it easier to roll back or revert if needed.

This is normally standard GitHub practice.

2024-10-27 18:16 UTC, aniruddhaadak80 commented
> Hey @aniruddhaadak80 no need to be sorry. You are doing great so far thanks !
> 
> If we have one feature / one fix / one issue per PR it will make it easier to roll back or revert if needed.
> 
> This is normally standard GitHub practice.

Okey ,I will follow this from now .

2024-10-27 18:23 UTC, jbampton commented
Can you resolve the conflicts ?

2024-10-27 18:35 UTC, jbampton commented
> Sorry , but I am unable to fix this for now .

We need to add a custom GitHub Action to run `ls-lint`.  

We don't want to run `ls-lint` with `pre-commit` as it is not supported.

2024-10-27 18:36 UTC, jbampton commented
@aniruddhaadak80 I fixed the conflicts now thanks

2024-10-29 07:22 UTC, jbampton commented
Hey @aniruddhaadak80 I fixed the conflicts

2024-10-29 11:53 UTC, aniruddhaadak80 commented
> Hey @aniruddhaadak80 I fixed the conflicts

That's great . 👍

2025-05-12 17:14 UTC, closed without merging